FROM python:alpine3.6

RUN pip install mongo-connector && pip install 'mongo-connector[elastic5]'

#CMD ["mongo-connector -m ${MONGO_URL} -t ${ES_URL} -d elastic2_doc_manager"]

COPY  start.sh /start.sh

RUN chmod  777 /start.sh

ENTRYPOINT ["/start.sh"]
