package com.usping.kdsn.bean;

import com.usping.kdsn.util.model.BaseEntity;

public class Comment extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_name
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_score
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    private Byte commentScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_date
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    private Long commentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.news_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    private String newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_content
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_name
     *
     * @return the value of comment.user_name
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_name
     *
     * @param userName the value for comment.user_name
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_score
     *
     * @return the value of comment.comment_score
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public Byte getCommentScore() {
        return commentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_score
     *
     * @param commentScore the value for comment.comment_score
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public void setCommentScore(Byte commentScore) {
        this.commentScore = commentScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_date
     *
     * @return the value of comment.comment_date
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public Long getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_date
     *
     * @param commentDate the value for comment.comment_date
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public void setCommentDate(Long commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.news_id
     *
     * @return the value of comment.news_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public String getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.news_id
     *
     * @param newsId the value for comment.news_id
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public void setNewsId(String newsId) {
        this.newsId = newsId == null ? null : newsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_content
     *
     * @return the value of comment.comment_content
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_content
     *
     * @param commentContent the value for comment.comment_content
     *
     * @mbg.generated Sat Nov 25 12:44:12 CET 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    public Comment() {
    }
}