package com.usping.kdsn.bean;

import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("Keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("Keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("Keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("Keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("Keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("Keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("Keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("Keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("Keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("Keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("Keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("Keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("Keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("Keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNull() {
            addCriterion("Company is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsNotNull() {
            addCriterion("Company is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEqualTo(String value) {
            addCriterion("Company =", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotEqualTo(String value) {
            addCriterion("Company <>", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThan(String value) {
            addCriterion("Company >", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("Company >=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThan(String value) {
            addCriterion("Company <", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLessThanOrEqualTo(String value) {
            addCriterion("Company <=", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyLike(String value) {
            addCriterion("Company like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotLike(String value) {
            addCriterion("Company not like", value, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyIn(List<String> values) {
            addCriterion("Company in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotIn(List<String> values) {
            addCriterion("Company not in", values, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyBetween(String value1, String value2) {
            addCriterion("Company between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andCompanyNotBetween(String value1, String value2) {
            addCriterion("Company not between", value1, value2, "company");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("Type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("Type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("Type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("Type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("Type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("Type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("Type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("Type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("Type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("Type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("Type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("Type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("Type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("Picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("Picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("Picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("Picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("Picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("Picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("Picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("Picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("Picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("Picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("Picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("Picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("Picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("Picture not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andAssortment1IsNull() {
            addCriterion("Assortment1 is null");
            return (Criteria) this;
        }

        public Criteria andAssortment1IsNotNull() {
            addCriterion("Assortment1 is not null");
            return (Criteria) this;
        }

        public Criteria andAssortment1EqualTo(String value) {
            addCriterion("Assortment1 =", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1NotEqualTo(String value) {
            addCriterion("Assortment1 <>", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1GreaterThan(String value) {
            addCriterion("Assortment1 >", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1GreaterThanOrEqualTo(String value) {
            addCriterion("Assortment1 >=", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1LessThan(String value) {
            addCriterion("Assortment1 <", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1LessThanOrEqualTo(String value) {
            addCriterion("Assortment1 <=", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1Like(String value) {
            addCriterion("Assortment1 like", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1NotLike(String value) {
            addCriterion("Assortment1 not like", value, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1In(List<String> values) {
            addCriterion("Assortment1 in", values, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1NotIn(List<String> values) {
            addCriterion("Assortment1 not in", values, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1Between(String value1, String value2) {
            addCriterion("Assortment1 between", value1, value2, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment1NotBetween(String value1, String value2) {
            addCriterion("Assortment1 not between", value1, value2, "assortment1");
            return (Criteria) this;
        }

        public Criteria andAssortment2IsNull() {
            addCriterion("Assortment2 is null");
            return (Criteria) this;
        }

        public Criteria andAssortment2IsNotNull() {
            addCriterion("Assortment2 is not null");
            return (Criteria) this;
        }

        public Criteria andAssortment2EqualTo(String value) {
            addCriterion("Assortment2 =", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2NotEqualTo(String value) {
            addCriterion("Assortment2 <>", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2GreaterThan(String value) {
            addCriterion("Assortment2 >", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2GreaterThanOrEqualTo(String value) {
            addCriterion("Assortment2 >=", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2LessThan(String value) {
            addCriterion("Assortment2 <", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2LessThanOrEqualTo(String value) {
            addCriterion("Assortment2 <=", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2Like(String value) {
            addCriterion("Assortment2 like", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2NotLike(String value) {
            addCriterion("Assortment2 not like", value, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2In(List<String> values) {
            addCriterion("Assortment2 in", values, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2NotIn(List<String> values) {
            addCriterion("Assortment2 not in", values, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2Between(String value1, String value2) {
            addCriterion("Assortment2 between", value1, value2, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment2NotBetween(String value1, String value2) {
            addCriterion("Assortment2 not between", value1, value2, "assortment2");
            return (Criteria) this;
        }

        public Criteria andAssortment3IsNull() {
            addCriterion("Assortment3 is null");
            return (Criteria) this;
        }

        public Criteria andAssortment3IsNotNull() {
            addCriterion("Assortment3 is not null");
            return (Criteria) this;
        }

        public Criteria andAssortment3EqualTo(String value) {
            addCriterion("Assortment3 =", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3NotEqualTo(String value) {
            addCriterion("Assortment3 <>", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3GreaterThan(String value) {
            addCriterion("Assortment3 >", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3GreaterThanOrEqualTo(String value) {
            addCriterion("Assortment3 >=", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3LessThan(String value) {
            addCriterion("Assortment3 <", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3LessThanOrEqualTo(String value) {
            addCriterion("Assortment3 <=", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3Like(String value) {
            addCriterion("Assortment3 like", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3NotLike(String value) {
            addCriterion("Assortment3 not like", value, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3In(List<String> values) {
            addCriterion("Assortment3 in", values, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3NotIn(List<String> values) {
            addCriterion("Assortment3 not in", values, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3Between(String value1, String value2) {
            addCriterion("Assortment3 between", value1, value2, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment3NotBetween(String value1, String value2) {
            addCriterion("Assortment3 not between", value1, value2, "assortment3");
            return (Criteria) this;
        }

        public Criteria andAssortment4IsNull() {
            addCriterion("Assortment4 is null");
            return (Criteria) this;
        }

        public Criteria andAssortment4IsNotNull() {
            addCriterion("Assortment4 is not null");
            return (Criteria) this;
        }

        public Criteria andAssortment4EqualTo(String value) {
            addCriterion("Assortment4 =", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4NotEqualTo(String value) {
            addCriterion("Assortment4 <>", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4GreaterThan(String value) {
            addCriterion("Assortment4 >", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4GreaterThanOrEqualTo(String value) {
            addCriterion("Assortment4 >=", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4LessThan(String value) {
            addCriterion("Assortment4 <", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4LessThanOrEqualTo(String value) {
            addCriterion("Assortment4 <=", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4Like(String value) {
            addCriterion("Assortment4 like", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4NotLike(String value) {
            addCriterion("Assortment4 not like", value, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4In(List<String> values) {
            addCriterion("Assortment4 in", values, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4NotIn(List<String> values) {
            addCriterion("Assortment4 not in", values, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4Between(String value1, String value2) {
            addCriterion("Assortment4 between", value1, value2, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment4NotBetween(String value1, String value2) {
            addCriterion("Assortment4 not between", value1, value2, "assortment4");
            return (Criteria) this;
        }

        public Criteria andAssortment5IsNull() {
            addCriterion("Assortment5 is null");
            return (Criteria) this;
        }

        public Criteria andAssortment5IsNotNull() {
            addCriterion("Assortment5 is not null");
            return (Criteria) this;
        }

        public Criteria andAssortment5EqualTo(String value) {
            addCriterion("Assortment5 =", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5NotEqualTo(String value) {
            addCriterion("Assortment5 <>", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5GreaterThan(String value) {
            addCriterion("Assortment5 >", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5GreaterThanOrEqualTo(String value) {
            addCriterion("Assortment5 >=", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5LessThan(String value) {
            addCriterion("Assortment5 <", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5LessThanOrEqualTo(String value) {
            addCriterion("Assortment5 <=", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5Like(String value) {
            addCriterion("Assortment5 like", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5NotLike(String value) {
            addCriterion("Assortment5 not like", value, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5In(List<String> values) {
            addCriterion("Assortment5 in", values, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5NotIn(List<String> values) {
            addCriterion("Assortment5 not in", values, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5Between(String value1, String value2) {
            addCriterion("Assortment5 between", value1, value2, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment5NotBetween(String value1, String value2) {
            addCriterion("Assortment5 not between", value1, value2, "assortment5");
            return (Criteria) this;
        }

        public Criteria andAssortment6IsNull() {
            addCriterion("Assortment6 is null");
            return (Criteria) this;
        }

        public Criteria andAssortment6IsNotNull() {
            addCriterion("Assortment6 is not null");
            return (Criteria) this;
        }

        public Criteria andAssortment6EqualTo(String value) {
            addCriterion("Assortment6 =", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6NotEqualTo(String value) {
            addCriterion("Assortment6 <>", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6GreaterThan(String value) {
            addCriterion("Assortment6 >", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6GreaterThanOrEqualTo(String value) {
            addCriterion("Assortment6 >=", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6LessThan(String value) {
            addCriterion("Assortment6 <", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6LessThanOrEqualTo(String value) {
            addCriterion("Assortment6 <=", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6Like(String value) {
            addCriterion("Assortment6 like", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6NotLike(String value) {
            addCriterion("Assortment6 not like", value, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6In(List<String> values) {
            addCriterion("Assortment6 in", values, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6NotIn(List<String> values) {
            addCriterion("Assortment6 not in", values, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6Between(String value1, String value2) {
            addCriterion("Assortment6 between", value1, value2, "assortment6");
            return (Criteria) this;
        }

        public Criteria andAssortment6NotBetween(String value1, String value2) {
            addCriterion("Assortment6 not between", value1, value2, "assortment6");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 20 16:46:11 CET 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}