package com.usping.kdsn.bean;

public class TaskWithBLOBs extends Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Summary
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.content
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Summary
     *
     * @return the value of task.Summary
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Summary
     *
     * @param summary the value for task.Summary
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.content
     *
     * @return the value of task.content
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.content
     *
     * @param content the value for task.content
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}