package com.usping.kdsn.bean;

public class UserWithBLOBs extends User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.workexperience
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String workexperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.projectexperience
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String projectexperience;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.workexperience
     *
     * @return the value of user.workexperience
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getWorkexperience() {
        return workexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.workexperience
     *
     * @param workexperience the value for user.workexperience
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setWorkexperience(String workexperience) {
        this.workexperience = workexperience == null ? null : workexperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.projectexperience
     *
     * @return the value of user.projectexperience
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getProjectexperience() {
        return projectexperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.projectexperience
     *
     * @param projectexperience the value for user.projectexperience
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setProjectexperience(String projectexperience) {
        this.projectexperience = projectexperience == null ? null : projectexperience.trim();
    }
}