package com.usping.kdsn.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.industry
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.assortment
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String assortment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reward_points
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private Float rewardPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userrole
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private Integer userrole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.joblocation
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String joblocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.school
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.industry
     *
     * @return the value of user.industry
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.industry
     *
     * @param industry the value for user.industry
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.assortment
     *
     * @return the value of user.assortment
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getAssortment() {
        return assortment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.assortment
     *
     * @param assortment the value for user.assortment
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setAssortment(String assortment) {
        this.assortment = assortment == null ? null : assortment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reward_points
     *
     * @return the value of user.reward_points
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public Float getRewardPoints() {
        return rewardPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reward_points
     *
     * @param rewardPoints the value for user.reward_points
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setRewardPoints(Float rewardPoints) {
        this.rewardPoints = rewardPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userrole
     *
     * @return the value of user.userrole
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public Integer getUserrole() {
        return userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userrole
     *
     * @param userrole the value for user.userrole
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setUserrole(Integer userrole) {
        this.userrole = userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.joblocation
     *
     * @return the value of user.joblocation
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getJoblocation() {
        return joblocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.joblocation
     *
     * @param joblocation the value for user.joblocation
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setJoblocation(String joblocation) {
        this.joblocation = joblocation == null ? null : joblocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.school
     *
     * @return the value of user.school
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.school
     *
     * @param school the value for user.school
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Mon Nov 20 16:46:11 CET 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}